# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test

default:
  tags:
    - q7r

# https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node16.14.0-chrome99-ff97/Dockerfile
# https://github.com/cypress-io/cypress-docker-images/blob/master/base/16.14.0-slim/Dockerfile

cypress:
  image: cypress/browsers:node16.14.0-chrome99-ff97
  stage: test
  script:
    - apt-get update && apt-get install -y git
    # - git --version
    # npm package installation requires git from package.json
    - npm install
    - npx cypress run --browser firefox 

# sast:
#   stage: test

# include:
# - template: Security/SAST.gitlab-ci.yml
# - template: Security/Dependency-Scanning.gitlab-ci.yml
