# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
- build
- test
- deploy-review
- deployQA
- dast

build-review:
  # node docker image on which this would be run
  image: node:16.17.0-alpine3.16
  stage: build
  script:
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 2 weeks
  only:
    - branches
    - merge_requests
  tags:
    - build

build-production:
  # node docker image on which this would be run
  image: node:16.17.0-alpine3.16
  stage: build
  script:
    - echo $PROD_TOKEN
    - echo $PROD_QUOTE
    - echo $PROD_FAUCET
    - echo $PROD_CHAIN_ID
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$PROD_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$PROD_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$PROD_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$PROD_CHAIN_ID'" >> .env
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 2 weeks
  only:
    - tags
    - branches
    - merge_requests
  tags:
    - build

build-QA:
  # node docker image on which this would be run
  image: node:16.17.0-alpine3.16
  stage: build
  script:
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 2 weeks
  only:
    - tags
    - branches
    - merge_requests
  tags:
    - build

docker_build:
  image: docker:stable
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f dev.Dockerfile -t $IMAGE .
    - docker push $IMAGE
  only:
    - branches
    - merge_requests

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - branches
  tags:
    - sonar-check

deploy_review:
  dependencies:
    - build-review
    - sonarcloud-check
    - sast
  stage: deploy-review
  script:
    - pm2 del nex-review || true
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install 
    - pm2 start npm --name nex-review -- run start
    - echo "http://$CI_ENVIRONMENT_SLUG.$APPS_DOMAIN" > environment_url.txt
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$APPS_DOMAIN
  artifacts:
    paths:
      - environment_url.txt
  only:
    - merge_requests
  except:
    - main
  tags:
    - deploy-review

stop_review_app:
  stage: deploy-review
  script: stop-review-app
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  except:
    - main
  tags:
    - deploy-review
  when: manual

deployToQA:
  stage: deployQA
  dependencies:
    - build-QA
  script: 
    - pm2 del nex-QA || true
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install 
    - pm2 start npm --name nex-QA -- run start
  when: manual 
  tags:
    - deploy

dast:
  stage: dast
  before_script:
    - if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then export DAST_WEBSITE=$(cat environment_url.txt); else export DAST_WEBSITE=$DAST_WEBSITE; fi
  artifacts:
    paths: 
      - gl-dast-report.json
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: always
  - if: '$CI_COMMIT_REF_NAME == "develop"'
    when: always
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - if: '$CI_COMMIT_REF_NAME != "develop"'
    when: never
  - if: '$CI_COMMIT_REF_NAME != "main"'
    when: never
  
