# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  # - qqqq
  - test

default:
  tags:
    - q7r33


# before_script:
#   - echo "yooooo"

# aaajob:
#   image: cypress/browsers:node16.14.0-chrome99-ff97
#   stage: test
#   script:
#     - mkdir vendor/
#     - echo "build" > vendor/hello.txt
#   cache:
#     key: build-cache
#     paths:
#       - vendor/
#   after_script:
#     - echo "afterrrr"

# bbbjob:
#   image: cypress/browsers:node16.14.0-chrome99-ff97
#   stage: test
#   dependencies:
#     - aaajob
#   script:
#     - cat vendor/hello.txt
#   cache:
#     key: build-cache
#     paths:
#       - vendor/


  
# https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node16.14.0-chrome99-ff97/Dockerfile
# https://github.com/cypress-io/cypress-docker-images/blob/master/base/16.14.0-slim/Dockerfile

install-cypress:
  image: cypress/browsers:node16.14.0-chrome99-ff97
  stage: .pre         # always first, no matter if it is listed in stages
  cache:
    key: NPM_DOWNLOAD_CACHE  # a single-key-4-all-branches for install jobs
    paths:
      - .npm/
  before_script:
    - apt-get update && apt-get install -y git
    - cp .env.example .env
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline
    # cat .npm/okok
    # - mkdir .npm
    # - echo "okok" > .npm/okok
  artifacts:
    paths:
    - .env
    - node_modules/

cypress:
  stage: test
  image: cypress/browsers:node16.14.0-chrome99-ff97
  needs:
  - job: install-cypress
    artifacts: true       # true by default, grabs `node_modules`
  script:

    # - git --version
    # npm package installation requires git from package.json
    # - npm install
    # - npx cypress run --browser firefox 

    # - du -sh node_modules
    # - ls node_modules/
    - ls .npm

# sast:
#   stage: test

# include:
# - template: Security/SAST.gitlab-ci.yml
# - template: Security/Dependency-Scanning.gitlab-ci.yml
