stages:
  - build_test
  - test



cypress_build:
  stage: build_test
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  variables:
    BASE_SLUG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - pwd
    - ls -alF
    - docker info
    - echo $IMAGE
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || true
    - docker build -f Dockerfile.cypress --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    #- docker build --cache-from $BASE_SLUG_IMAGE:latest --tag $BASE_SLUG_IMAGE:$CI_COMMIT_SHA --tag $BASE_SLUG_IMAGE:latest .
    #- docker push $BASE_SLUG_IMAGE:$CI_COMMIT_SHA
    #- docker push $BASE_SLUG_IMAGE:latest

cypress_test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    #- npx cypress run
    #- ./node_modules/.bin/cypress run
    - pwd
    - ls -alF
    - cd /app
    - ./node_modules/.bin/cypress run

# cypress_test2:
  # stage: test
  # image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  # script:
    #- npx cypress run
    #- ./node_modules/.bin/cypress run --browser firefox
    # - pwd
    # - ls -alF


# need artifacts with expiry

# sha1 on both package files, tag as combined sha1

# run again ###