# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: DAST.gitlab-ci.yml
- template: Security/Container-Scanning.gitlab-ci.yml

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
- build
- test
- deploy-review
- deployQA
- dast


build-review:
  # node docker image on which this would be run
  image: node:16.17.0-alpine3.16
  stage: build
  script:
    - apk update && apk add g++ make nasm git libtool autoconf automake libpng-dev pkgconfig
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 2 weeks
  only:
    - branches
    - merge_requests
  tags:
    - build

docker_build:
  image: docker:stable
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f dev.Dockerfile -t $IMAGE .
    - docker push $IMAGE

npm-audit:
  image: "registry.gitlab.com/gitlab-org/security-products/analyzers/npm-audit:1.4.0"
  stage: test
  variables:
    TOOL: npm
  script:
    - /analyzer run
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      - gl-dependency-scanning-report.json
  tags: 
    - npm-audit

sast:
  stage: test

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - branches
  tags:
    - sonar-check

deploy_review:
  dependencies:
    - build-review
    - npm-audit
    - sonarcloud-check
    - sast
  stage: deploy-review
  script:
    - pm2 del nex-review || true
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install 
    - pm2 start npm --name nex-review -- run start
    - echo "http://$CI_ENVIRONMENT_SLUG.$APPS_DOMAIN" > environment_url.txt
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$APPS_DOMAIN
  only:
    - merge_requests
  except:
    - main
  tags:
    - deploy-review

stop_review_app:
  stage: deploy-review
  script: stop-review-app
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only: 
    - branches
  except:
    - dev
  tags:
    - deploy-review
  when: manual

deployToQA:
  stage: deployQA
  dependencies:
    - build-review
  script: 
    - pm2 del nex-QA || true
    - echo "NEXT_PUBLIC_DEFAULT_TOKEN='$DEV_TOKEN'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_QUOTE='$DEV_QUOTE'" >> .env
    - echo "NEXT_PUBLIC_FAUCET_URL='$DEV_FAUCET'" >> .env
    - echo "NEXT_PUBLIC_DEX_URL='$DEV_DEX_URL'" >> .env
    - echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID='$DEV_CHAIN_ID'" >> .env
    - echo "NEXT_PUBLIC_BLOCKCHAIN_ENDPOINTS='$DEV_BLOCKCHAIN_ENDPOINTS'" >> .env
    - npm install 
    - pm2 start npm --name nex-QA -- run start
  only: 
    - merge_requests
  when: manual 
  tags:
    - deploy

dast:
  stage: dast
  before_script:
    - if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then export DAST_WEBSITE=$(cat environment_url.txt); else export DAST_WEBSITE=$DAST_WEBSITE; fi
  artifacts:
    paths: 
      - gl-dast-report.json
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: never
  - if: $CI_COMMIT_REF_NAME == "develop"
    when: manual
  - when: always